In [1]:
print('Hello')

Hello

In [2]:
2+3

5

In [3]:
print(for i in range(10))

SyntaxError: invalid syntax (3063344100.py, line 1)

In [5]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9

In [1]:
763638812/1210854977

0.6306608359425359

In [1]:
import pandas as pd

In [2]:
##df_csv=pd.read_csv('popularity.csv')
df_csv=pd.read_csv('popularity.csv',sep=',',header=0,na_values=['NA','N/A','--'],usecols=['url',' timedelta'],dtype={'url':str,' timedelta':float},nrows=10)
print(df_csv.head(20))

                                                 url   timedelta
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0
3  http://mashable.com/2013/01/07/astronaut-notre...       731.0
4   http://mashable.com/2013/01/07/att-u-verse-apps/       731.0
5   http://mashable.com/2013/01/07/beewi-smart-toys/       731.0
6  http://mashable.com/2013/01/07/bodymedia-armba...       731.0
7   http://mashable.com/2013/01/07/canon-poweshot-n/       731.0
8  http://mashable.com/2013/01/07/car-of-the-futu...       731.0
9  http://mashable.com/2013/01/07/chuck-hagel-web...       731.0

In [4]:
df=pd.DataFrame(df_csv)

In [5]:
df

                                                 url   timedelta
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0
3  http://mashable.com/2013/01/07/astronaut-notre...       731.0
4   http://mashable.com/2013/01/07/att-u-verse-apps/       731.0
5   http://mashable.com/2013/01/07/beewi-smart-toys/       731.0
6  http://mashable.com/2013/01/07/bodymedia-armba...       731.0
7   http://mashable.com/2013/01/07/canon-poweshot-n/       731.0
8  http://mashable.com/2013/01/07/car-of-the-futu...       731.0
9  http://mashable.com/2013/01/07/chuck-hagel-web...       731.0

In [19]:
df.to_csv('dummy_set_practive.csv',index=False,header=True)

In [7]:
# Data Cleaning 
df.head(3)

                                                 url   timedelta
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0

In [12]:
# Data Cleaning module 

csv_path='bank_marketing_updated_v1.csv'

df1=pd.read_csv(csv_path,sep=',',header=2,na_values=['NA','N/A','--'],usecols=['salary','balance'],nrows=5)

df1
if (df1['salary'] == 0).any():
    print("yes")

yes